spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://configuser:configpass@localhost:8888/api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.config.client: DEBUG