spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://configuser:configpass@192.168.100.197:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    org.springframework.cloud.config.client: DEBUG