server:
  port: 9093

spring:
  datasource:
    url: jdbc:h2:mem:clientsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
      template:
        exchange: command-client-exchange
        routing-key: client.create
      queue: command-create-client-queue
    publisher:
      exchange: client-exchange
      routing-key: client.created
      queue: client-queue

